export const GET_ERRORS = "GET_ERRORS";
export const GET_PROJECT_TASKS = "GET_PROJECT_TASKS";
export const GET_PROJECT_TASK = "GET_PROJECT_TASK";
export const DELETE_PROJECT_TASK = "DELETE_PROJECT_TASK";

export const GET_COMPANY_TASKS = "GET_COMPANY_TASKS";
export const GET_COMPANY_TASK = "GET_COMPANY_TASK";
export const DELETE_COMPANY_TASK = "DELETE_COMPANY_TASK";

export const GET_JOB_TASKS = "GET_JOB_TASKS";
export const GET_JOB_TASK = "GET_JOB_TASK";
export const DELETE_JOB_TASK = "DELETE_JOB_TASK";

export const GET_DEPARTMENT_TASKS = "GET_DEPARTMENT_TASKS";
export const GET_DEPARTMENT_TASK = "GET_DEPARTMENT_TASK";
export const DELETE_DEPARTMENT_TASK = "DELETE_DEPARTMENT_TASK";

export const GET_PROJECT_VIEWS = "GET_PROJECT_VIEWS";
export const GET_PROJECT_VIEW = "GET_PROJECT_VIEW";
export const DELETE_PROJECT_VIEW = "DELETE_PROJECT_VIEW";